### ISSUE TITLE
Make the navigation bar responsive

### ISSUE THREAD

**Issue by KhangPham9** [titan-rover/website#18]
Right now if we display the website in mobile mode, the navigation bar become really disfigured and the goal is to make it responsive by using css.

**Comment by olasores** [comment]
https://codepen.io/ngochuynh/pen/yKrvVZ

**Comment by KhangPham9** [comment]
This is a good reference for the navbar https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_topnav
